import test from 'node:test';
import assert from 'node:assert/strict';
import {Store} from './store.js';
import {Rewards,PRIZES,pickPrize} from './rewards.js';
import {handleRewards} from './roulette-ui.js';
function fixture(t,draw=()=>0){let now=Date.UTC(2026,8,24);const s=new Store(':memory:');t.after(()=>s.db.close());s.set('rewards:role','role');s.set('rewards:leveling','internal');return {s,r:new Rewards(s,{draw,now:()=>now}),advance:ms=>now+=ms};}
test('exact outcome weights, cash 0.1%',()=>{const counts={};for(let n=0;n<10000;n++){const p=pickPrize(n);counts[p.key]=(counts[p.key]||0)+1;}for(const p of PRIZES)assert.equal(counts[p.key],p.weight);assert.equal(PRIZES.filter(p=>p.cash).reduce((n,p)=>n+p.weight,0),10);assert.throws(()=>pickPrize(10000));});
test('role gate fails closed; no demo tickets',t=>{const {s,r}=fixture(t);assert.equal(r.account('u').tickets,0);assert.throws(()=>r.spin('u','a',['role']));r.grant('u','admin','g');assert.throws(()=>r.spin('u','a',[]));s.set('rewards:role','');assert.throws(()=>r.spin('u','a',['role']));assert.equal(r.account('u').tickets,1);});
test('grants/spins are idempotent and persisted',t=>{const {s,r}=fixture(t);r.grant('u','admin','g');r.grant('u','admin','g');assert.equal(r.account('u').tickets,1);const c=r.spin('u','a',['role']);assert.equal(r.spin('u','a',['role']).id,c.id);assert.equal(r.account('u').tickets,0);assert.equal(new Rewards(s).claims('u')[0].id,c.id);assert.throws(()=>r.spin('u','b',['role']));assert.equal(r.fulfill(c.id,'admin').changes,1);assert.equal(r.fulfill(c.id,'admin').changes,0);});
test('cash remains available beyond the former monthly cap',t=>{const {r,advance}=fixture(t);r.grant('u','a','g',10);for(let n=0;n<10;n++)assert.equal(r.spin('u',String(n),['role']).cash,25);assert.equal(r.spent(),250);assert.equal(r.claims('u').every(c=>c.prize==='cash25'),true);advance(32*86400000);r.grant('u','a','next-grant');assert.equal(r.spin('u','next',['role']).cash,25);});
test('XP cooldown, shared daily cap, milestone tickets',t=>{const {r,advance}=fixture(t);r.activity('u','chat');r.activity('u','chat');assert.equal(r.account('u').xp,15);for(let n=0;n<100;n++){r.activity('u','chat');r.activity('u','voice');advance(60000);}assert.equal(r.account('u').xp,600);assert.equal(r.account('u').tickets,0);advance(86400000);for(let n=0;n<40;n++){r.activity('u','chat');advance(60000);}assert.equal(r.account('u').xp,1200);assert.equal(r.account('u').tickets,1);});
test('admin actions reject regular members',async t=>{const {r}=fixture(t);let result;await handleRewards({customId:'reward:grant',user:{id:'u'},values:['u'],memberPermissions:{has:()=>false},editReply:async p=>result=p},r);assert.equal(r.account('u').tickets,0);assert.match(result.embeds[0].data.title,/للإدارة/);});

test('chat and voice XP are separate while total milestone tickets remain compatible',t=>{const {r}=fixture(t);r.activity('u','chat');r.activity('u','voice');const a=r.account('u');assert.equal(a.chat_xp,15);assert.equal(a.voice_xp,10);assert.equal(a.xp,25);});

test('tier requirements need both chat and voice thresholds',async()=>{const {RANK_TIERS,rankProgress}=await import('./rank-tiers.js');const xp=n=>100*n+25*n*(n-1);for(const tier of RANK_TIERS){const a={chat_xp:xp(tier.chat),voice_xp:xp(tier.voice)};assert.equal(rankProgress(a).current.name,tier.name);assert.notEqual(rankProgress({...a,chat_xp:a.chat_xp-1}).current?.name,tier.name);if(tier.voice)assert.notEqual(rankProgress({...a,voice_xp:a.voice_xp-1}).current?.name,tier.name);}});

test('rank syncing grants only qualified editable roles and preserves other roles',async t=>{const {r}=fixture(t);const {syncRanks}=await import('./rank-sync.js');const xp=n=>100*n+25*n*(n-1);r.account('u');r.db.prepare('UPDATE reward_accounts SET chat_xp=?,voice_xp=? WHERE user=?').run(xp(20),xp(5),'u');const added=[];const roles=new Map([['a',{id:'a',name:'Rookie',editable:true}],['b',{id:'b',name:'Skilled',editable:true}],['c',{id:'c',name:'Elite',editable:true}]]);const member={roles:{cache:new Map([['unrelated',{}]]),add:async id=>added.push(id)}};const guild={roles:{fetch:async()=>roles},members:{fetch:async()=>member,fetchMe:async()=>({})}};await syncRanks(guild,r,'u');assert.deepEqual(added,['a','b']);assert.equal(member.roles.cache.has('unrelated'),true);added.length=0;roles.set('duplicate',{id:'duplicate',name:'Rookie',editable:true});roles.get('b').editable=false;await syncRanks(guild,r,'u');assert.deepEqual(added,[]);});
