import test from 'node:test';
import assert from 'node:assert/strict';
import {Store} from './store.js';
import {Rewards,PRIZES,pickPrize} from './rewards.js';
import {handleRewards} from './roulette-ui.js';
function fixture(t,draw=()=>0){let now=Date.UTC(2026,8,24);const s=new Store(':memory:');t.after(()=>s.db.close());s.set('rewards:role','role');s.set('rewards:leveling','internal');return {s,r:new Rewards(s,{draw,now:()=>now}),advance:ms=>now+=ms};}
test('exact outcome weights, cash 0.1%',()=>{const counts={};for(let n=0;n<10000;n++){const p=pickPrize(n);counts[p.key]=(counts[p.key]||0)+1;}for(const p of PRIZES)assert.equal(counts[p.key],p.weight);assert.equal(PRIZES.filter(p=>p.cash).reduce((n,p)=>n+p.weight,0),10);assert.throws(()=>pickPrize(10000));});
test('role gate fails closed; no demo tickets',t=>{const {s,r}=fixture(t);assert.equal(r.account('u').tickets,0);assert.throws(()=>r.spin('u','a',['role']));r.grant('u','admin','g');assert.throws(()=>r.spin('u','a',[]));s.set('rewards:role','');assert.throws(()=>r.spin('u','a',['role']));assert.equal(r.account('u').tickets,1);});
test('grants/spins are idempotent and persisted',t=>{const {s,r}=fixture(t);r.grant('u','admin','g');r.grant('u','admin','g');assert.equal(r.account('u').tickets,1);const c=r.spin('u','a',['role']);assert.equal(r.spin('u','a',['role']).id,c.id);assert.equal(r.account('u').tickets,0);assert.equal(new Rewards(s).claims('u')[0].id,c.id);assert.throws(()=>r.spin('u','b',['role']));assert.equal(r.fulfill(c.id,'admin').changes,1);assert.equal(r.fulfill(c.id,'admin').changes,0);});
test('cash remains available beyond the former monthly cap',t=>{const {r,advance}=fixture(t);r.grant('u','a','g',10);for(let n=0;n<10;n++)assert.equal(r.spin('u',String(n),['role']).cash,25);assert.equal(r.spent(),250);assert.equal(r.claims('u').every(c=>c.prize==='cash25'),true);advance(32*86400000);r.grant('u','a','next-grant');assert.equal(r.spin('u','next',['role']).cash,25);});
test('XP cooldown, shared daily cap, and one ticket per level',t=>{const {r,advance}=fixture(t);r.activity('u','chat');r.activity('u','chat');assert.equal(r.account('u').xp,15);for(let n=0;n<100;n++){r.activity('u','chat');r.activity('u','voice');advance(60000);}assert.equal(r.account('u').xp,600);assert.equal(r.account('u').tickets,3);advance(86400000);for(let n=0;n<40;n++){r.activity('u','chat');advance(60000);}assert.equal(r.account('u').xp,1200);assert.equal(r.account('u').tickets,5);});
test('admin actions reject regular members',async t=>{const {r}=fixture(t);let result;await handleRewards({customId:'reward:grant',user:{id:'u'},values:['u'],memberPermissions:{has:()=>false},editReply:async p=>result=p},r);assert.equal(r.account('u').tickets,0);assert.match(result.embeds[0].data.title,/للإدارة/);});

test('chat and voice XP are separate while total milestone tickets remain compatible',t=>{const {r}=fixture(t);r.activity('u','chat');r.activity('u','voice');const a=r.account('u');assert.equal(a.chat_xp,15);assert.equal(a.voice_xp,10);assert.equal(a.xp,25);});

test('tier requirements need both chat and voice thresholds',async()=>{const {RANK_TIERS,rankProgress}=await import('./rank-tiers.js');const xp=n=>100*n+25*n*(n-1);for(const tier of RANK_TIERS){const a={chat_xp:xp(tier.chat),voice_xp:xp(tier.voice)};assert.equal(rankProgress(a).current.name,tier.name);assert.notEqual(rankProgress({...a,chat_xp:a.chat_xp-1}).current?.name,tier.name);if(tier.voice)assert.notEqual(rankProgress({...a,voice_xp:a.voice_xp-1}).current?.name,tier.name);}});
test('displayed next rank never repeats a rank the member already has',async()=>{const {displayedRankProgress}=await import('./rank-tiers.js');const progress=displayedRankProgress({chat_xp:0,voice_xp:0},[{id:'1541533396889510060',name:'Renamed'}]);assert.equal(progress.current.name,'Rookie');assert.equal(progress.next.name,'Skilled');});

test('rank syncing grants only qualified editable roles and preserves other roles',async t=>{const {r}=fixture(t);const {syncRanks}=await import('./rank-sync.js');const xp=n=>100*n+25*n*(n-1);r.account('u');r.db.prepare('UPDATE reward_accounts SET chat_xp=?,voice_xp=? WHERE user=?').run(xp(20),xp(5),'u');const added=[];const roles=new Map([['1541533396889510060',{id:'1541533396889510060',name:'Renamed Rookie',editable:true}],['1541533395392270388',{id:'1541533395392270388',name:'Skilled',editable:true}],['1541533393458831400',{id:'1541533393458831400',name:'Elite',editable:true}]]);const member={roles:{cache:new Map([['unrelated',{}]]),add:async id=>added.push(id)}};const guild={roles:{fetch:async()=>roles},members:{fetch:async()=>member,fetchMe:async()=>({})}};await syncRanks(guild,r,'u');assert.deepEqual(added,['1541533396889510060','1541533395392270388']);assert.equal(member.roles.cache.has('unrelated'),true);added.length=0;roles.set('duplicate',{id:'duplicate',name:'Rookie',editable:true});roles.get('1541533395392270388').editable=false;await syncRanks(guild,r,'u');assert.deepEqual(added,['1541533396889510060']);});

test('tag match requires enabled identity for this guild, not matching tag text',async()=>{const {hasServerTag}=await import('./tag-rewards.js');assert.equal(hasServerTag({primaryGuild:{identityEnabled:true,identityGuildId:'g',tag:'rize'}},'g'),true);assert.equal(hasServerTag({primaryGuild:{identityEnabled:true,identityGuildId:'other',tag:'rize'}},'g'),false);assert.equal(hasServerTag({primaryGuild:{identityEnabled:false,identityGuildId:'g'}},'g'),false);assert.equal(hasServerTag({primaryGuild:null},'g'),false);});
test('level lookup is source-specific and paginated',async t=>{const {r}=fixture(t);const {levelMembers}=await import('./member-admin.js');for(let n=0;n<12;n++){r.account(String(n));r.db.prepare('UPDATE reward_accounts SET chat_xp=3250 WHERE user=?').run(String(n));}assert.equal(levelMembers(r,'chat',10).total,12);assert.equal(levelMembers(r,'chat',10).rows.length,10);assert.equal(levelMembers(r,'chat',10,1).rows.length,2);assert.equal(levelMembers(r,'voice',10).total,0);assert.throws(()=>levelMembers(r,'invalid',10));});

test('tag role is removed whenever tag is absent, including manual grants',async t=>{const {r}=fixture(t);const {syncTag}=await import('./tag-rewards.js');r.store.set('tag:role','tag');const roles=new Map();let tagged=true;const role={id:'tag',name:'Supporter',editable:true,permissions:{has:()=>false}};const member={user:{bot:false},roles:{cache:roles,add:async id=>roles.set(id,role),remove:async id=>roles.delete(id)}};const guild={id:'g',roles:{fetch:async()=>role},members:{fetchMe:async()=>({}),fetch:async()=>member},client:{users:{fetch:async()=>({primaryGuild:{identityEnabled:tagged,identityGuildId:'g'}})}}};await syncTag(guild,r,'u');assert.equal(roles.has('tag'),true);tagged=false;await syncTag(guild,r,'u');assert.equal(roles.has('tag'),false);roles.set('tag',role);await syncTag(guild,r,'u');assert.equal(roles.has('tag'),false);});

test('XP uses normal rates even if a caller supplies a multiplier',t=>{const {r}=fixture(t);r.activity('u','chat',2);r.activity('u','voice',2);assert.equal(r.account('u').chat_xp,15);assert.equal(r.account('u').voice_xp,10);});

function interaction(user='u',admin=false){let result;return {user:{id:user},guild:{members:{fetch:async()=>({roles:{cache:new Map([['role',{}]])}})}},memberPermissions:{has:()=>admin},editReply:async p=>{result=p;},get result(){return result;}};}
test('staff alerts survive failed delivery and send only once after success',async t=>{const {r}=fixture(t);const {sendPrizeAlerts,STAFF_CHANNEL}=await import('./prize-alerts.js');r.grant('u','a','g');r.spin('u','n',['role']);r.spin('u','n',['role']);let fail=true;const sent=[];const guild={channels:{fetch:async id=>{assert.equal(id,STAFF_CHANNEL);return {isTextBased:()=>true,send:async p=>{if(fail)throw Error('offline');sent.push(p);return {id:'message'};}};}}};await assert.rejects(()=>sendPrizeAlerts(guild,r));fail=false;await sendPrizeAlerts(guild,r);await sendPrizeAlerts(guild,r);assert.equal(sent.length,1);assert.match(sent[0].content,/<@u>/);assert.equal(sent[0].embeds[0].data.fields[0].value,'٢٥ دولار');});
test('a rewarded level cannot pay twice after restart, XP rollback or mixed activity',t=>{const {s,r,advance}=fixture(t);r.account('u');r.db.prepare('UPDATE reward_accounts SET xp=90 WHERE user=?').run('u');r.activity('u','chat');assert.equal(r.account('u').tickets,1);r.activity('u','voice');assert.equal(r.account('u').tickets,1);r.db.prepare('UPDATE reward_accounts SET xp=90 WHERE user=?').run('u');advance(60000);r.activity('u','chat');assert.equal(r.account('u').tickets,1);const restarted=new Rewards(s,{now:()=>Date.UTC(2026,8,26)});r.db.prepare('UPDATE reward_accounts SET xp=90 WHERE user=?').run('u');restarted.activity('u','voice');assert.equal(r.account('u').tickets,1);r.db.prepare('UPDATE reward_accounts SET xp=240 WHERE user=?').run('u');restarted.activity('u','chat');assert.equal(r.account('u').tickets,2);});
test('legacy milestone counters do not mint old tickets on ordinary activity',t=>{const {r,advance}=fixture(t);r.account('u');r.db.prepare('UPDATE reward_accounts SET xp=1000,milestones=1,tickets=2 WHERE user=?').run('u');r.activity('u','chat');assert.equal(r.account('u').tickets,2);r.db.prepare('UPDATE reward_accounts SET xp=1340 WHERE user=?').run('u');advance(60000);r.activity('u','chat');assert.equal(r.account('u').tickets,3);advance(60000);r.activity('u','chat');assert.equal(r.account('u').tickets,3);});
test('spin requires confirmation, rejects other users, and double clicks spend once',async t=>{const {r}=fixture(t);r.grant('u','a','g',5);const i=interaction();i.customId='reward:spin';await handleRewards(i,r);assert.equal(r.account('u').tickets,5);const id=i.result.components[0].components[0].data.custom_id;const other=interaction('other');other.customId=id;await handleRewards(other,r);assert.equal(r.claims('other').length,0);i.customId=id;await handleRewards(i,r);await handleRewards(i,r);assert.equal(r.account('u').tickets,4);assert.equal(r.claims('u').length,1);assert.match(i.result.embeds[0].data.image.url,/roulette-v3-cash25/);});
test('role is checked again when confirming a spin',async t=>{const {r}=fixture(t);r.grant('u','a','g');const i=interaction();i.customId='reward:spin';await handleRewards(i,r);i.customId=i.result.components[0].components[0].data.custom_id;i.guild.members.fetch=async()=>({roles:{cache:new Map()}});await assert.rejects(()=>handleRewards(i,r));assert.equal(r.account('u').tickets,1);});
test('admin grant and delivery require explicit confirmation and remain idempotent',async t=>{const {r}=fixture(t);const i=interaction('admin',true);i.customId='reward:grant:5';i.values=['u'];await handleRewards(i,r);assert.equal(r.account('u').tickets,0);i.customId=i.result.components[0].components[0].data.custom_id;await handleRewards(i,r);await handleRewards(i,r);assert.equal(r.account('u').tickets,5);const c=r.spin('u','draw',['role']);i.customId=`reward:deliver:${c.id}`;await handleRewards(i,r);assert.equal(r.claims('u')[0].status,'pending');i.customId=i.result.components[0].components[0].data.custom_id;await handleRewards(i,r);assert.equal(r.claims('u')[0].status,'delivered');});
